ObervatorioDeFeminicidios/Observatorio

- .env.example
- app/api/hello/route.js
- app/libs/mysql.js
- package-lock.json
- package.json
- Add libraries for connect to MySQL
- Configuration to MySQL  with the connection data in a  file env.local (env.example)
- Implementation of API Hello route
Jira Card: [OB-1](https://imakia.atlassian.net/jira/software/projects/OB/boards/5?selectedIssue=OB-1)
[OB-1]: https://imakia.atlassian.net/browse/OB-1?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OB-1 loading environment variables

- app/libs/multistep-form.ts
- app/page.tsx
- components/form/field/input.tsx
- components/form/field/select.tsx
- components/form/form.tsx
- components/form/navigation.tsx
- components/form/step.tsx
- components/form/steps.tsx
- Implementing the registration form by using the libraries: Shacdn, Zod, and react-hook-form
- Extracting all the elements into components
- Generating the form schema and default values dynamically
Jira Card: [OB-4](https://imakia.atlassian.net/browse/OB-4)
[OB-4]: https://imakia.atlassian.net/browse/OB-4?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OB-4 Implementing the form

- app/api/form/route.ts
- app/utils/transform-object.ts
- types.d.ts
Adding new values to the list
Jira Card: [OB-15](https://imakia.atlassian.net/browse/OB-15)
[OB-15]: https://imakia.atlassian.net/browse/OB-15?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OB-15 Adding new values to the list

- app/utils/transform-object.ts
- components/form/field/select.tsx
- lib/mock-data.ts
Small fixes
Jira Card: [OB-17](https://imakia.atlassian.net/browse/OB-17)
[OB-17]: https://imakia.atlassian.net/browse/OB-17?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OB-17 Small fixes

- app/utils/transform-object.ts
- tsconfig.json
> Fixing types

- lib/mysql.ts
Adjusting quieries, adding lable z.uso, and z.tabla_referencia, and fixes in the queries. 
Jira Card: [OB-13](https://imakia.atlassian.net/browse/OB-13)
[OB-13]: https://imakia.atlassian.net/browse/OB-13?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OB-13 adjusting quieries

- components/form/confirmation.tsx
- components/form/field/date.tsx
- components/form/form.tsx
- components/form/navigation.tsx
- lib/mysql.ts
- package-lock.json
- package.json
- store/registration-form.ts
- Avoid SQL injection
- Fix the date in the date picker component
- Validate the last step data
- Scroll to top on clicking the next button
Jira Card: [OB-28](https://imakia.atlassian.net/browse/OB-28)
[OB-28]: https://imakia.atlassian.net/browse/OB-28?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OB-28 Avoid SQL injection

- actions/_auth.ts
- app/registration/page.tsx
- components/Header.tsx
- components/LoginForm.tsx
- components/LogoutButton.tsx
- components/form/confirmation.tsx
- components/form/navigation.tsx
- components/form/steps.tsx
- lib/mysql.ts
- store/registration-form.ts
Adding loading, success, and error states
Jira Card: [OB-22](https://imakia.atlassian.net/browse/OB-22)
[OB-22]: https://imakia.atlassian.net/browse/OB-22?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OB-22 Adding loading, success and error states

- actions/_form.ts
- components/form/field/select.tsx
- lib/mysql.ts
- types.d.ts
Filtering the municipality and postal code lists
Jira Card: [OB-20](https://imakia.atlassian.net/browse/OB-20)
[OB-20]: https://imakia.atlassian.net/browse/OB-20?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OB-20 Filtering the municipality and postal code lists

- actions/_form.ts
- components/form/field/select-empty.tsx
Fixing the error flow when adding a new option
Jira Card: [OB-31](https://imakia.atlassian.net/browse/OB-31)
[OB-31]: https://imakia.atlassian.net/browse/OB-31?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OB-31 Fix error flow

- lib/form.ts
Adding predefined values to form fields based on new requirement
Jira Card: [OB-33](https://imakia.atlassian.net/browse/OB-33)
[OB-33]: https://imakia.atlassian.net/browse/OB-33?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OB-33 Adding predefined values

- components/form/field/select-empty.tsx
Fixing the validation when the field is not updatable
Jira Card: [OB-37](https://imakia.atlassian.net/browse/OB-37)
[OB-37]: https://imakia.atlassian.net/browse/OB-37?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OB-37 Fixing the validation

- components/form/field/select.tsx
Resetting dependent fields after selection: department, municipality, and postal code.
Jira Card: [OB-32](https://imakia.atlassian.net/browse/OB-32)
[OB-32]: https://imakia.atlassian.net/browse/OB-32?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OB-32 Reseting dependent fields after selection

- components/form/confirmation.tsx
- components/form/form-step.tsx
- components/form/form.tsx
- components/form/navigation.tsx
- components/form/steps.tsx
- store/registration-form.ts
Fixing the issue with the back button
Jira Card: [OB-36](https://imakia.atlassian.net/browse/OB-36)
[OB-36]: https://imakia.atlassian.net/browse/OB-36?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OB-36 Fixing the issue with the back button

- app/api/registration/route.ts
- components/form/confirmation.tsx
Implementing the POST method through the API instead of server actions
> Implementing the POST method throught the API

- app/api/registration/route.ts
- components/form/confirmation.tsx
Switching to API from server action to insert the register in the database
> Switching the POST action to API

- app/dashboard/layout.tsx
- components/Sidebar.tsx
- components/form/step.tsx
- components/form/steps.tsx
- components/ui/sheet.tsx
- package-lock.json
- package.json
Adding responsive design to the sidebar and form steps
Jira Card: [OB-48](https://imakia.atlassian.net/browse/OB-48)
[OB-48]: https://imakia.atlassian.net/browse/OB-48?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OB-48 Adding responsive design

- package-lock.json
- package.json
Updating some dependencies, the main one was next due to high vulnerabilities.
Jira Card: [OB-46](https://imakia.atlassian.net/browse/OB-46)
[OB-46]: https://imakia.atlassian.net/browse/OB-46?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OB-46 Updating some dependencies

- actions/_form.ts
- app/api/index.ts
- app/api/registration/route.ts
- app/dashboard/history/columns.tsx
- app/dashboard/history/data-table.tsx
- app/dashboard/history/page.tsx
- app/dashboard/layout.tsx
- app/login/page.tsx
- auth.config.ts
- components/Header.tsx
- components/form/confirmation.tsx
- components/ui/table.tsx
- lib/definitions.ts
- lib/mysql.ts
- package-lock.json
- package.json
- Adding the table to the history tab
- Adding the id of the inserted register
Jira Card: [OB-47](https://imakia.atlassian.net/browse/OB-47)
[OB-47]: https://imakia.atlassian.net/browse/OB-47?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OB-47 Adding table and inserted id

- app/dashboard/history/columns.tsx
- lib/mysql.ts
Adjusting the limit and date field for the initial release
Jira Card: [OB-62](https://imakia.atlassian.net/browse/OB-62)
[OB-62]: https://imakia.atlassian.net/browse/OB-62?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OB-62 Adjusting the limit and date field for the initial release

- components/form/confirmation.tsx
- lib/form.ts
Adjusting the form and confirmation data
Jira Card: [OB-63](https://imakia.atlassian.net/browse/OB-63)
[OB-63]: https://imakia.atlassian.net/browse/OB-63?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OB-63 Adjusting the form and confirmation data

- components/form/confirmation.tsx
- lib/form.ts
- lib/mysql.ts
> First adjustments

- actions/_form.ts
- app/api/index.ts
- app/api/registration/route.ts
- app/dashboard/history/data-table.tsx
- app/dashboard/registers/[id]/page.tsx
- components/form/confirmation.tsx
- components/form/field/select-multiple.tsx
- components/form/form.tsx
- components/form/navigation.tsx
- lib/definitions.ts
- lib/form.ts
- lib/mysql.ts
- store/registration-form.ts
Edit feature
Jira Card: [OB-65](https://imakia.atlassian.net/browse/OB-65)
[OB-65]: https://imakia.atlassian.net/browse/OB-65?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OB-65 Edit feature

- actions/_form.ts
- app/dashboard/history/column-filter.tsx
- app/dashboard/history/columns.tsx
- app/dashboard/history/data-table.tsx
- app/dashboard/history/page.tsx
- app/dashboard/layout.tsx
- lib/mysql.ts
- types.d.ts
- util/debounced-input.tsx
Implementing the column filters
Jira Card: [OB-55](https://imakia.atlassian.net/browse/OB-55)
[OB-55]: https://imakia.atlassian.net/browse/OB-55?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OB-55 Implementing the column filters

- components/form/field/date.tsx
- components/form/field/input.tsx
- components/form/navigation.tsx
- lib/form.ts
- package-lock.json
- package.json
Multiple fixes
Jira Card: [OB-51](https://imakia.atlassian.net/browse/OB-51)
[OB-51]: https://imakia.atlassian.net/browse/OB-51?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OB-51 Multiple fixes

- .gitignore
- actions/_auth.ts
- actions/_form.ts
- app/dashboard/history/data-table.tsx
- app/dashboard/page.tsx
- app/global-error.tsx
- auth.config.ts
- components/LoginForm.tsx
- components/LogoutButton.tsx
- components/form/field/input.tsx
- components/form/field/select.tsx
- components/form/form-step.tsx
- components/ui/textarea.tsx
- instrumentation.ts
- lib/form.ts
- next.config.mjs
- package-lock.json
- package.json
- sentry.client.config.ts
- sentry.edge.config.ts
- sentry.server.config.ts
- types.d.ts
Fixing multiple issues and integrating Sentry
Jira Card: [OB-76](https://imakia.atlassian.net/browse/OB-76)
Jira Card: [OB-67](https://imakia.atlassian.net/browse/OB-67)
[OB-76]: https://imakia.atlassian.net/browse/OB-76?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OB-67]: https://imakia.atlassian.net/browse/OB-67?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OB-67 Issues OB-76 Sentry

- components/form/confirmation.tsx
- components/form/field/select.tsx
- components/form/navigation.tsx
Enable the update button and some code refactors
Jira Card: [OB-81](https://imakia.atlassian.net/browse/OB-81)
[OB-81]: https://imakia.atlassian.net/browse/OB-81?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OB-81 Enable the update button and some code refactors

- app/dashboard/history/column-filter.tsx
- app/dashboard/history/columns.tsx
- app/dashboard/history/data-table.tsx
- app/dashboard/history/page.tsx
- app/dashboard/layout.tsx
- app/globals.css
- components/form/form.tsx
- components/ui/data-table/pagination.tsx
- tailwind.config.ts
- Adding columns
- New clean design with new colors, scroll areas and better spacing
Jira Card: [OB-83](https://imakia.atlassian.net/browse/OB-83)
[OB-83]: https://imakia.atlassian.net/browse/OB-83?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OB-83 Adding columns

- package-lock.json
Update dependencies
Jira Card: [OB-87](https://imakia.atlassian.net/browse/OB-87)
[OB-87]: https://imakia.atlassian.net/browse/OB-87?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OB-87 Update dependencies

- app/dashboard/history/data-table.tsx
- app/dashboard/history/loading.tsx
- app/dashboard/registers/[id]/loading.tsx
- app/dashboard/registration/loading.tsx
- app/layout.tsx
- components/Sidebar.tsx
- components/form/field/date.tsx
- components/form/field/input.tsx
- components/form/field/select-multiple.tsx
- components/form/field/select.tsx
- components/form/form.tsx
- components/table/filters/column-filter.tsx
- components/table/filters/date-range-picker.tsx
- components/table/loaders/headers.tsx
- components/table/loaders/rows.tsx
- lib/table.tsx
- package-lock.json
- package.json
- Fixing spacings
- Adding the date range picker component
- Implementing loaders and a new font family
- Replace single quotes in the text area
Jira Card: [OB-59](https://imakia.atlassian.net/browse/OB-59)
[OB-59]: https://imakia.atlassian.net/browse/OB-59?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OB-59 Frontend improvements

- app/dashboard/history/data-table.tsx
- Improve readability
Jira Card: [OB-59](https://imakia.atlassian.net/browse/OB-59)
[OB-59]: https://imakia.atlassian.net/browse/OB-59?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OB-59 Improve readability

- components/form/field/select.tsx
Enhance FieldSelect component to handle 'nacionalidad' option setting dependent fields based on selected value
Jira Card: [OB-88](https://imakia.atlassian.net/browse/OB-88)
[OB-88]: https://imakia.atlassian.net/browse/OB-88?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OB-88 Enhance FieldSelect component to handle 'nacionalidad' option

- app/dashboard/history/data-table.tsx
- components/form/field/select.tsx
> User requirement

- components/form/field/select.tsx
- components/form/form.tsx
- components/form/navigation.tsx
> Fixing form reloading

- components/table/columns.tsx
Add formatDate function to format date strings for table columns
> Add formatDate function to format date strings for table columns

- util/format-date.tsx
Add timeZone option to formatDate for consistent date formatting
> Add timeZone option to formatDate for consistent date formatting

- app/dashboard/registers/[id]/page.tsx
- components/form/confirmation.tsx
- components/form/form.tsx
- components/form/navigation.tsx
- util/providers.tsx
Refactor query keys and improve data fetching in registration forms and history, fixing cache issues after updating a register.
Jira Card: [OB-90](https://imakia.atlassian.net/browse/OB-90)
[OB-90]: https://imakia.atlassian.net/browse/OB-90?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OB-90 Refactor query keys and improve data fetching in registration forms and history

- app/dashboard/registers/[id]/page.tsx
- components/form/confirmation.tsx
- components/form/form.tsx
- components/form/navigation.tsx
- util/format-date.tsx
- util/providers.tsx
> Fix cache issue

- app/dashboard/history/page.tsx
- app/dashboard/registers/[id]/page.tsx
- components/form/confirmation.tsx
- components/form/form.tsx
- util/get-query-client.ts
- util/providers.tsx
Fixing editing issues
Jira Card: [OB-90](https://imakia.atlassian.net/browse/OB-90)
[OB-90]: https://imakia.atlassian.net/browse/OB-90?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OB-90 Fixing editing issues
